connect_four/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from game_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'' , include("game_app.urls")),
    url(r'^$' , views.index, name="index"),
]

game_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from game_app import views

app_name = 'game_app'
urlpatterns = [
    # url(r'^connect_four/', views.game, name="game"),
    url(r'^create/', views.GameCreateView.as_view(), name="create"),
    url(r'^connect_four/', views.ScoreCreateView.as_view(), name="game"),
    url(r'^leaders_board/', views.ScoreListView.as_view(), name="scores")
]

game_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Game(models.Model):

    player_1_name = models.CharField(max_length=50)
    player_2_name = models.CharField(max_length=50)

    def __str__(self):
        return f"Game {self.pk}"

    def get_absolute_url(self):
        return reverse("game_app:game")


class Score(models.Model):
    player_name = models.CharField(max_length=50)
    moves = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.player_name} {self.moves}"

    def get_absolute_url(self):
        return reverse("game_app:create")

game_app/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from game_app import models

# Create your views here.
def index(request):
    return render(request, 'game_app/index.html', {})


# def game(request):
#     my_object = models.Game.objects.last()
#     my_dict = {'player1' : my_object.player_1_name, 'player2' : my_object.player_2_name}
#     return render(request, 'game_app/connect_four.html', context=my_dict)

class ScoreListView(ListView):
    # context_object_name = 'scores'
    model = models.Score
    template_name = 'game_app/leaders_board.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['scores'] = models.Score.objects.order_by('moves')[0:10]
        return context


class ScoreCreateView(CreateView):
    model = models.Score
    fields = "__all__"
    template_name = "game_app/connect_four.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['player1'] = models.Game.objects.last().player_1_name
        context['player2'] = models.Game.objects.last().player_2_name
        return context


class GameCreateView(CreateView):
    fields = "__all__"
    model = models.Game

game_app/templates/game_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Connect Four</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'game_app/connect_four.css' %}" media="screen" title="no title" charset="utf-8">
    <link href="https://fonts.googleapis.com/css2?family=Galada&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
        <div class="container">
          <ul class="nav navbar-nav">
            <li class="navbar-brand" ><img src="https://www.logolynx.com/images/logolynx/04/04e3f399f686e98a363c7cb5036ed0ae.png" width="125" height="45" alt="" /></li>
            <li class="item px-2 pt-2" ><a class="link" href="{% url 'index' %}">Home</a></li>
            <li class="item px-2 pt-2" ><a class="link" href="{% url 'game_app:scores' %}">Leaders Board</a></li>
            <li class="item px-2 pt-2" ><a class="link" href="{% url 'admin:index' %}">Admin</a></li>
          </ul>
        </div>
      </nav>
          {% block body_block %}

          {% endblock %}

    </div>
  </body>
</html>

game_app/templates/game_app/connect_four.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block body_block %}


        <div class="jumbotron">
          <h1 class="display-4 text-center">Welcome to Connect Four</h1>
          <p id="lead" class="lead text-center">The objective of this game is to connect four of your chips!</p>
          <p id="playerone" class="lead text-center">{{player1}}</p>
          <p id="playertwo" class="lead text-center">{{player2}}</p>
          <form class="restart" method="post">
            {% csrf_token %}
             <!-- <label for="playername">Name: </label><input id="label1" type="text" name="playername" value="">
             <label for="moves">Moves:</label><input id="label2" type="text" name="moves" value=""> -->
             {{form.as_p}}
            <input type="submit" class="btn btn-success" value="Press to Restart the game!">
          </form>
        </div>

      <table class="gameboard" align="center">
        <tr>
          <td class="row1 column1 circle col1"></td>
          <td class="row1 column2 circle col2"></td>
          <td class="row1 column3 circle col3"></td>
          <td class="row1 column4 circle col4"></td>
          <td class="row1 column5 circle col5"></td>
          <td class="row1 column6 circle col6"></td>
          <td class="row1 column7 circle col7"></td>
        </tr>
        <tr>
          <td class="row2 column1 circle col1"></td>
          <td class="row2 column2 circle col2"></td>
          <td class="row2 column3 circle col3"></td>
          <td class="row2 column4 circle col4"></td>
          <td class="row2 column5 circle col5"></td>
          <td class="row2 column6 circle col6"></td>
          <td class="row2 column7 circle col7"></td>
        </tr>
        <tr>
          <td class="row3 column1 circle col1"></td>
          <td class="row3 column2 circle col2"></td>
          <td class="row3 column3 circle col3"></td>
          <td class="row3 column4 circle col4"></td>
          <td class="row3 column5 circle col5"></td>
          <td class="row3 column6 circle col6"></td>
          <td class="row3 column7 circle col7"></td>
        </tr>
        <tr>
          <td class="row4 column1 circle col1"></td>
          <td class="row4 column2 circle col2"></td>
          <td class="row4 column3 circle col3"></td>
          <td class="row4 column4 circle col4"></td>
          <td class="row4 column5 circle col5"></td>
          <td class="row4 column6 circle col6"></td>
          <td class="row4 column7 circle col7"></td>
        </tr>
        <tr>
          <td class="row5 column1 circle col1"></td>
          <td class="row5 column2 circle col2"></td>
          <td class="row5 column3 circle col3"></td>
          <td class="row5 column4 circle col4"></td>
          <td class="row5 column5 circle col5"></td>
          <td class="row5 column6 circle col6"></td>
          <td class="row5 column7 circle col7"></td>
        </tr>
        <tr>
          <td class="row6 column1 circle col1"></td>
          <td class="row6 column2 circle col2"></td>
          <td class="row6 column3 circle col3"></td>
          <td class="row6 column4 circle col4"></td>
          <td class="row6 column5 circle col5"></td>
          <td class="row6 column6 circle col6"></td>
          <td class="row6 column7 circle col7"></td>
        </tr>

      </table>
  <script src="/static/game_app/connect_four.js"></script>
{% endblock %}

game_app/templates/game_app/game_form.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block body_block %}


<div class="jumbotron">
  <h1 class="display-4 text-center">Welcome to Connect Four</h1>
  <p id="lead" class="lead text-center">Please register first to play the game!</p>

  <form class="register_form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" name="" value="Register">
  </form>
</div>

{% endblock %}

game_app/templates/game_app/index.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block body_block %}


<div class="jumbotron">
    <h1 class="display-4 text-center">Welcome to Connect Four</h1>
    <form class="register_form" action="{% url 'game_app:create' %}" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" name="" value="Click here to register">
  </form>

  <!-- <a class="board" href="{% url 'game_app:scores' %}"><button class="btn btn-primary"  type="button" >Leaders Board</button></a> -->

</div>

{% endblock %}

game_app/templates/game_app/leaders_board.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
  <h1 class="display-4 text-center">Welcome to Leaders Board!</h1>

  <table class="leadertable" align="center">
    <thead>
      <td class="cell">Player Name</td>
      <td class="cell">No. of moves</td>
    </thead>
    {% for score in scores %}
    <tr class="leaderrow">
      <td class="cell">{{score.player_name}}</td>
      <td class="cell">{{score.moves}}</td>
    </tr>
    {% endfor %}
  </table>
</div>

{% endblock %}